import Head from 'next/head'
import CheckCircleIcon from '@material-ui/icons/CheckCircle';
import styles from '../styles/Home.module.css'
// Making our button look cool hehe
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
import AddTask from '../components/AddTask';
import { UserContext } from '../components/UserContext'
import * as actionTypes from '../store/actions/actionTypes';

const Header = () => {
    
    return (
        <div>
            <Head>
                <title>To Do List!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>
              Welcome to your custom <a>To Do List!</a>
            </h1>

            <p className={styles.description}>
              To edit this input, visit our edit page{' '}
              <code className={styles.code}>http://localhost:3000/edit</code>
              or simply click
              <Button href="http://localhost:3000/edit" color="primary">here</Button>
            </p>
        </div>  
        
    );
} 

export default Header;